spring:
  application:
    name: apiGateway
server:
  port: 8086
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
zuul:
  routes:
    myproduct:
      path: /myProduct/**
      serviceId: product
      sensitiveHeaders:
