spring:
  application:
    name: configServer
  rabbitmq:
    host: 192.168.189.128
    port: 5672
    username: root
    password: 123456
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Shell?serverTimezone=UTC
#  jpa:
#    show-sql: true
server:
  port: 8083
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
env: dev
